### ISSUE TITLE
Deleting the workspace in IDE is not deleting the workspace from local PC (where docker installed) directory

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#318]
If the workspace is deleted from IDE, the same should be deleted from the server PC also. Because, as developer, if I want to create new workspace with the same name, the previously deleted workspace and the projects will be loaded.

**Comment by eivantsov** [comment]
Duplicate of https://github.com/eclipse/che/issues/3973

**Comment by vinokurig** [comment]
Fixed in https://github.com/eclipse/che/issues/3973

**Comment by v-prabhu** [comment]
This issue still persists with v.1.4.0. 
However, if we create the workspace without any sample projects, then deleting the workspace deletes from :/data folder as well.

Follow the scenario below to reproduce the issue:
1) Create a workspace "Test-Workspace" with sample project "artik-samples".
2) After workspace is up and running delete the workspace.
3) Observe the "workspaces" folder in :/data. The folder "Test-Workspace" still exists.

**Comment by eivantsov** [comment]
Related - https://github.com/codenvy/artik/issues/324

**Comment by v-prabhu** [comment]
Windows-10 screen capture:
https://youtu.be/mjCrN4xWpgY

**Comment by eivantsov** [comment]
Fixed in Che

**Comment by v-prabhu** [comment]
@eivantsov Can you please help me to know whether I can verify this fix with the nightly build or should I wait for the next release?

**Comment by eivantsov** [comment]
I will let you know when a new release is available.
