### ISSUE TITLE
Not able to start debugging session

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik#328]
1) Connect the device
2) Compile one of the project file
3) Click Debug.
4) Terminal log stuck at creating the PID and stopped. Debugging did not continue
![debugging stuck](https://cloud.githubusercontent.com/assets/21373498/22672474/1423e99e-ec89-11e6-9393-6356853d92d6.PNG)

**Comment by eivantsov** [comment]
![image](https://cloud.githubusercontent.com/assets/5337267/22679587/e12a7070-ed0b-11e6-96fd-826a32a76c21.png)

I think we need a screenshare sessions to fix it. I have hard time reproducing any issues related to device connectivity.

**Comment by v-prabhu** [comment]
@eivantsov I found a scenario to reproduce this issue.
1) Create a workspace with some sample project (ex: artik-sample)
2) Connect to any Artik device.
3) Select any file in the project and click debug in the connected device.
4) Terminal shows error "Can not exec a.out:No such file or directory" (This is expected as the file is not yet compiled).
5) Again select the same file in project and click compile.
6) a.out will be created. Again select the file and click debug in connected device.
7) Debugging stops in the beginning itself. Can not end the debugging session or continue.

![debugging stuck](https://cloud.githubusercontent.com/assets/21373498/22804975/4bbbec32-eed0-11e6-8793-8e7ee565c7ec.PNG)

Please check the video below:
https://youtu.be/aV5-yWB7F7U

**Comment by v-prabhu** [comment]
After this developer can not end the debug session or kill the PID. User has to reboot the Artik device to start debugging again.

**Comment by eivantsov** [comment]
Yes, confirmed. I think what we will do is check if binary exists and if it does not - never attempt to start gdb and connect with a debugger to that process.

**Comment by eivantsov** [comment]
Fixed

**Comment by v-prabhu** [comment]
Thanks. Fixed in 1.4.0-SNAPSHOT, cli: nightly.

**Comment by v-prabhu** [comment]
@eivantsov This issue still persists in Mac installer. Please give same fix as provided to other platforms.

**Comment by eivantsov** [comment]
It is not yet released. Artik installer uses tagged versions.
